---
services:
  # === SYSTEM METRICS ===
  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.10.2
    pid: host
    restart: unless-stopped
    ports: ["10.0.0.245:9100:9100"]
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.udev.data=/host/run/udev/data"
      - "--web.listen-address=0.0.0.0:9100"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
    container_name: smartctl-exporter
    restart: unless-stopped
    privileged: true
    user: root
    ports: ["10.0.0.245:9633:9633"]

  # === CONTAINER METRICS ===
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    restart: unless-stopped
    privileged: true
    ports: ["10.0.0.245:8080:8080"]
    devices: ["/dev/kmsg"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--store_container_labels=false"
