---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terragrunt CD
permissions: { contents: read }

on:
  workflow_dispatch: {}
  schedule: [{cron: '0 0 * * *'}] # Every day at midnight
  push:
    branches: ["main"]
    paths:
      - root.hcl
      - infrastructure/**
      - terraform/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  TG_NON_INTERACTIVE: "true"
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  apply:
    runs-on: infra-runners
    environment: TrueNAS
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with: { cache: false }

      - name: Load Secrets
        uses: ./.github/actions/load-secrets
        with:
          op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Terragrunt Init
        run: terragrunt run --all -- init -upgrade

      - name: Terragrunt Apply
        run: terragrunt run --all -- apply -auto-approve
